### ISSUE TITLE
TavilyWebSearch not work 

### ISSUE THREAD

**Issue by lijingcheng2021** [om-ai-lab/OmAgent#134]
Traceback (most recent call last):
  File "/home/li_jingcheng/项目/OmAgent/examples/step2_outfit_with_switch/run_cli.py", line 55, in <module>
    cli_client.start_interactor()
  File "/home/li_jingcheng/code/OmAgent/omagent-core/src/omagent_core/clients/devices/cli/client.py", line 49, in start_interactor
    self._task_handler_interactor = TaskHandler(worker_config=worker_config, workers=self._workers)
  File "/home/li_jingcheng/code/OmAgent/omagent-core/src/omagent_core/engine/automator/task_handler.py", line 66, in __init__
    workers.extend([worker_cls(**config) for _ in range(concurrency)])
  File "/home/li_jingcheng/code/OmAgent/omagent-core/src/omagent_core/engine/automator/task_handler.py", line 66, in <listcomp>
    workers.extend([worker_cls(**config) for _ in range(concurrency)])
  File "/home/li_jingcheng/anaconda3/envs/omagent/lib/python3.10/site-packages/pydantic_settings/main.py", line 167, in __init__
    super().__init__(
  File "/home/li_jingcheng/anaconda3/envs/omagent/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/home/li_jingcheng/anaconda3/envs/omagent/lib/python3.10/site-packages/pydantic_settings/main.py", line 167, in __init__
    super().__init__(
  File "/home/li_jingcheng/anaconda3/envs/omagent/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/home/li_jingcheng/code/OmAgent/omagent-core/src/omagent_core/tool_system/manager.py", line 69, in init_tools
    t = registry.get_tool(tool["name"])
  File "/home/li_jingcheng/code/OmAgent/omagent-core/src/omagent_core/utils/registry.py", line 74, in get
    return self._get(category, name)
  File "/home/li_jingcheng/code/OmAgent/omagent-core/src/omagent_core/utils/registry.py", line 56, in _get
    raise KeyError(f"Module {name} not found in category {category}")
KeyError: 'Module TavilyWebSearch not found in category tool'

**Comment by lijingcheng2021** [comment]
i find not do  pip install -e omagent-core😂
